# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

run:
  name: "flexible-moderate"

scenario:
  ll:
  - v1.15
  clusters:
  - 48
  sector_opts:
  - Co2L0.45-1H-T-H-B-I
  planning_horizons:
  - 2030

sector:
  district_heating:
    progress:
      2030: 0.0
  retrofitting:
    retro_endogen: true 
  tes: true
  boilers: true
  biomass_boiler: false
  micro_chp: true
  regional_coal_demand: true
  use_fischer_tropsch_waste_heat: false
  use_haber_bosch_waste_heat: false
  use_methanolisation_waste_heat: false
  use_methanation_waste_heat: false
  use_fuel_cell_waste_heat: true
  use_electrolysis_waste_heat: false
  biomass_spatial: true
  biomass_transport: true

costs:
  year: 2025

solving:
  solver_options:
    gurobi-default:
      threads: 8
      BarConvTol: 1.e-4
