# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

plotting:
  clusters: 48
  planning_horizon: [2020, 2030, 2040, 2050]
  time_resolution: "12H"
  sector_opts: "T-H-B-I"

heat_pumps:
  residential_decentral: 7.5 # (kW_el) https://iea.blob.core.windows.net/assets/4713780d-c0ae-4686-8c9b-29e782452695/TheFutureofHeatPumps.pdf
  services: 20 # (kW_el) https://iea.blob.core.windows.net/assets/4713780d-c0ae-4686-8c9b-29e782452695/TheFutureofHeatPumps.pdf
  central: 100 # (kW_el) https://iea.blob.core.windows.net/assets/4713780d-c0ae-4686-8c9b-29e782452695/TheFutureofHeatPumps.pdf

set_capacities:
  clusters: 48
  planning_horizon: "2040" # "2040" (2030->2040), "2050" (2040->2050)
  time_resolution: "12H"
  scenario: ["flexible", "retro_tes", "flexible-moderate", "rigid"]
  sector_opts: "T-H-B-I"

moderate_retrofitting:
  clusters: 48
  planning_horizon: "2030"
  time_resolution: "12H"
  sector_opts: "T-H-B-I"
