# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

plotting:
  clusters: 48
  planning_horizon: [2020, 2030, 2040, 2050]
  sector_opts: "dist2.0-T-H-B-I"

heat_pumps:
  residential_decentral: 7.5 # (kW_el) https://iea.blob.core.windows.net/assets/4713780d-c0ae-4686-8c9b-29e782452695/TheFutureofHeatPumps.pdf
  services: 20 # (kW_el) https://iea.blob.core.windows.net/assets/4713780d-c0ae-4686-8c9b-29e782452695/TheFutureofHeatPumps.pdf
  central: 100 # (kW_el) https://iea.blob.core.windows.net/assets/4713780d-c0ae-4686-8c9b-29e782452695/TheFutureofHeatPumps.pdf

set_capacities:
  clusters: 48
  planning_horizon: "2040" # "2040" (2030->2040), "2050" (2040->2050)
  scenario: ["flexible", "retro_tes", "flexible-moderate", "rigid"]

moderate_retrofitting:
  clusters: 48
  planning_horizon: "2030"

improve_cops_after_renovation:
  clusters: 48
  planning_horizon: "2030"
  scenario: ["flexible", "retro_tes", "flexible-moderate"]
