# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

plotting:
  clusters: 48
  planning_horizon: [2030, 2040, 2050]
  time_resolution: "100H"

heat_pumps:
  max_capacity: 6900 # https://www.energysage.com/electricity/house-watts/how-many-watts-does-an-air-source-heat-pump-use/
  min_capacity: 830 # https://www.energysage.com/electricity/house-watts/how-many-watts-does-an-air-source-heat-pump-use/

set_capacities:
  clusters: 48
  planning_horizon: "2030"
  time_resolution: "100H"
  scenario: ["flexible", "retro_tes", "flexible-moderate", "rigid "]
