# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

plotting:
  clusters: 48
  planning_horizon: [2030, 2040, 2050]
  time_resolution: "100H"

heat_pumps:
  max_capacity: 6900 # https://www.energysage.com/electricity/house-watts/how-many-watts-does-an-air-source-heat-pump-use/
  min_capacity: 830 # https://www.energysage.com/electricity/house-watts/how-many-watts-does-an-air-source-heat-pump-use/

set_capacities:
  clusters: 48
  planning_horizon: "2040" # "2040" (2030->2040), "2050" (2040->2050)
  time_resolution: "100H"
  scenario: ["flexible", "retro_tes", "flexible-moderate", "rigid"]

moderate_retrofitting:
  clusters: 48
  planning_horizon: "2030"
  time_resolution: "100H"
